### ISSUE TITLE
Firecracker Robot Tests

### ISSUE THREAD

**Issue by Ichmed** [Elektrobit/flake-pilot#151]
In order to run firecracker tests in GitHub actions we need a publicly available and stable way to install firecracker on the runner.

**Comment by schaefi** [comment]
I suggest to use a custom container which includes firecracker. Such a container can be found here

* https://build.opensuse.org/package/show/home:marcus.schaefer:delta_containers/test-os

I think we can reference this container in a github action like this

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/home/marcus.schaefer/delta_containers/images_15.4/flakeos:latest
    steps:
        ...
```

I haven't tested this but it should pull the container and allows to run the workflow. Missing components, e.g the robot framework can either be added inside of the container or installed by the action inside of the container instance. For performance reasons it might be better to add the framework into the container imho

But there is probably another issue.

Running firecracker requires KVM, meaning the runner must expose ```/dev/kvm``` and I doubt that this is done by the github runners. If we cannot have a runner with KVM support we need to host our own runner. This would require some infrastructure to maintain.

Thus this issue can cause some headaches
